[package]
name = "advance"
version = "0.1.0"
authors = ["Yuri Kunde Schlesner <yuriks@yuriks.net>"]

[profile.release]
debug = true

[dependencies]
byteorder = "1.2.6"
num = "0.2.0"
sdl2 = "0.31.0"
futures-preview = "0.3.0-alpha.7"
